config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :nominations, only: [:index, :show], defaults: { format: :json } do
      collection do
        get 'random'
      end
      member do
        post 'vote'
      end
    end
  end

  devise_for :users
  resources :nominations do
    collection do
      post 'verify_all'
      patch 'merge'
      get 'full_report'
      get 'shortlist'
      get 'shortlist_report'
    end
  end

  resources :institutions

  scope '/api' do
    resources :institutions, only: [:index, :show], defaults: { format: :json }
  end

  root 'nominations#index'

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :nominations,
    dependent: :restrict_with_error,
    inverse_of: :institution

  validates :abbreviation, uniqueness: true

  scope :ordered, -> { order(priority: :desc, name: :asc) }
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = @institutions.ordered
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :abbreviation, :priority)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
  <% if @institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% @institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.abbreviation %></td>
        <td><%= institution.priority %></td>
        <td><%= link_to 'Show', institution %></td>
        <% if can? :edit, institution %>
          <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <% end %>
        <% if can? :destroy, institution %>
          <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @institution.abbreviation %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @institution.priority %>
</p>

<% if can? :edit, @institution %>
  <%= link_to 'Edit', edit_institution_path(@institution) %> |
<% end %>
<%= link_to 'Back', institutions_path %>