config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :nominations, only: [:index, :show], defaults: { format: :json } do
      collection do
        get 'random'
      end
      member do
        post 'vote'
      end
    end
  end

  devise_for :users
  resources :nominations do
    collection do
      post 'verify_all'
      patch 'merge'
      get 'full_report'
      get 'shortlist'
      get 'shortlist_report'
    end
  end

  resources :institutions

  scope '/api' do
    resources :institutions, only: [:index, :show], defaults: { format: :json }
  end

  root 'nominations#index'

end

app/models/nomination.rb
class Nomination < ActiveRecord::Base
  belongs_to :institution, counter_cache: true
  has_many :reasons, inverse_of: :nomination, dependent: :destroy
  has_many :attachments, inverse_of: :nomination, dependent: :destroy

  accepts_nested_attributes_for :reasons, :attachments,
    allow_destroy: true,
    reject_if: :all_blank

  validates :institution, presence: true
  validates :name, presence: true
  validates :year_of_birth, numericality: { only_integer: true, greater_than: 1799, less_than: 2000, allow_blank: true }

  scope :verified_reasons, -> { reasons.where(verified: true) }

  scope :ordered, -> { order(name: :asc) }
  scope :verified, -> { joins(:reasons).where(reasons: { verified: true }).uniq }

  scope :ten_random, -> { order('RANDOM()').limit(10) }

  scope :search, ->(txt) { where('LOWER(name) LIKE ?', "%#{txt.downcase}%") }

  scope :sorted_by, lambda {|sort_key|
    direction = (sort_key =~ /desc$/) ? 'desc' : 'asc'
    case sort_key.to_s
    when /^name/
      order(name: direction)
    when /^institution/
      joins(:institution).order("institutions.name #{direction}")
    when /^votes/
      order(votes: direction)
    when /^reasons/
      order("reasons_count #{direction}")
    else
      raise ArgumentError, "Invalid sort option '#{sort_key}'"
    end
  }

  def age
    return nil unless self.year_of_birth.is_a? Integer
    Date.today.year - self.year_of_birth
  end

  def rank
    index = Nomination.order(votes: :desc).pluck(:votes).find_index do |v|
      self.votes >= v
    end

    if index.nil?
      # Database changed since record loaded, just return last place
      Nomination.count
    else
      index + 1
    end
  end

  def verified?
    reasons.where(verified: true).any?
  end

  def eat!(target)
    target.reasons.each do |r|
      r.nomination = self
      r.save!
    end

    self.votes += target.votes

    self.gender = target.gender if gender.blank?
    self.year_of_birth = target.year_of_birth if year_of_birth.blank?
    self.branch = target.branch if branch.blank?

    save!

    target.reload.destroy
  end


  def self.per_page
    20
  end
end

app/controllers/api/nominations_controller.rb
class Api::NominationsController < ApplicationController
  respond_to :json
  protect_from_forgery with: :null_session

  # GET /api/nominations
  def index
    @nominations = Nomination.all
    if params["institution"]
      @nominations = @nominations.where(institution_id: params["institution"])
    elsif params["search"]
      @nominations = @nominations.search(params['search'])
    end
  end

  # GET /api/nominations/1
  def show
    @nomination = Nomination.find(params["id"])
  rescue
    render json: { error: 'not found'}, status: :not_found
  end

  # GET /api/nominations/random
  def random
    @nominations = Nomination.ten_random
    render :index
  end

  # POST /api/nominations/1/vote
  def vote
    @nomination = Nomination.find(params["id"])
    Nomination.increment_counter(:votes, params["id"])
    render :show, status: :ok, location: api_nomination_path
  rescue
    render json: { error: 'not found' }, status: :not_found
  end
end

app/controllers/nominations_controller.rb
class NominationsController < ApplicationController
  before_action :set_nomination, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource # also loads @nomination[s]
  protect_from_forgery

  # GET /nominations
  # GET /nominations.json
  # GET /nominations[.json]?institution=1
  def index
    if params["sort"]
      @sort_params = params["sort"]
      @nominations = @nominations.sorted_by(params["sort"])
    else
      @sort_params = "name asc"
      @nominations = @nominations.order(name: 'asc')
    end

    if params["institution"]
      @nominations = @nominations.where(institution_id: params["institution"])
    end

    if params["search"]
      @nominations = @nominations.search(params['search'])
    end

    respond_to do |format|
      format.json
      format.html do
        @nominations = @nominations.page(params[:page])
        render :index
      end
    end
  end

  def shortlist
    if params["sort"]
      @sort_params = params["sort"]
      @nominations = @nominations.sorted_by(params["sort"])
    else
      @sort_params = "name asc"
      @nominations = @nominations.order(name: 'asc')
    end

    @nominations = @nominations.where(shortlisted: true).page(params[:page])
    @title = "Shortlist"
    render :index
  end

  def shortlist_report
    @nominations = @nominations.where(shortlisted: true).order(name: 'asc')
    @title = "Kortlisterapport"
  end

  # GET /nominations/full_report
  def full_report
    @nominations = @nominations.verified.order(:name)
  end

  # GET /nominations/1
  # GET /nominations/1.json
  def show
  end

  # GET /nominations/new
  def new
    @nomination = Nomination.new
  end

  # GET /nominations/1/edit
  def edit
    @nomination.attachments.build
  end

  # POST /nominations
  # POST /nominations.json
  def create
    @nomination = Nomination.new(nomination_params)
    @nomination.reasons.each {|r| r.verified = false }

    respond_to do |format|
      if @nomination.save
        format.html { redirect_to @nomination, notice: 'Nomination was successfully created.' }
        format.json { render :show, status: :created, location: @nomination }
      else
        format.html { render :new }
        format.json { render json: @nomination.errors.full_messages.join(";"), status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nominations/merge
  def merge
    nom = Nomination.find(params["ids"])
    keeper = nom.shift
    nom.each do |n|
      keeper.eat!(n)
    end

    redirect_to keeper, notice: "#{nom.count + 1} records merged into one"
  rescue
    redirect_to nominations_url, notice: "An error occured during merge"
  end

  # PATCH/PUT /nominations/1
  # PATCH/PUT /nominations/1.json
  def update
    respond_to do |format|
      if @nomination.update(nomination_params)
        format.html { redirect_to @nomination, notice: 'Nomination was successfully updated.' }
        format.json { render :show, status: :ok, location: @nomination }
      else
        format.html { render :edit }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH /nominations/verify_all
  def verify_all
    Reason.update_all(verified: true)
    redirect_to nominations_url, notice: 'All verified'
  rescue
    redirect_to nominations_url, notice: 'Error occured.'
  end

  # DELETE /nominations/1
  # DELETE /nominations/1.json
  def destroy
    @nomination.destroy
    respond_to do |format|
      format.html { redirect_to nominations_url, notice: 'Nomination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nomination
      @nomination = Nomination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nomination_params
      params.require(:nomination).
        permit(:institution_id, :name, :gender, :branch, :year_of_birth,
               :shortlisted, :shortlist_reason, :documentation,
               reasons_attributes:
                 %i|id _destroy reason nominator nominator_email verified|,
               attachments_attributes: %i|id _destroy file|)
    end
end

app/helpers/api/nominations_helper.rb
module Api::NominationsHelper
end

app/helpers/nominations_helper.rb
module NominationsHelper
  def personalia(nomination)
    [
      case(nomination.gender)
      when "Male" then "♂"
      when "Female" then "♀"
      else nil
      end,
      nomination.age ? "#{nomination.age} år" : nil,
      nomination.branch.blank? ? nil : nomination.branch
    ].compact.join(", ")
  end

  def sorting_link(name, key, default_dir='asc')
    if @sort_params && @sort_params.split[0] == key
      current_sortdir = @sort_params.split[1]
      dir = (current_sortdir == 'desc') ? 'asc' : 'desc'
    else
      dir = default_dir
    end

    link_to name, params.merge({sort: "#{key} #{dir}"}), class: "sortable #{current_sortdir}"
  end

  def merge_reasons(nomination)
    nomination.reasons.map do |r|
      simple_format(r.reason, {}, wrapper_tag: 'blockquote') +
        content_tag(:p, "– #{r.nominator}", class: 'nominator')
    end.join.html_safe
  end

end

app/views/nominations/_form.html.erb
<%= form_for(@nomination, html: { multipart: true }) do |f| %>
  <% if @nomination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nomination.errors.count, "error") %> prohibited this nomination from being saved:</h2>

      <ul>
      <% @nomination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :institution_id %><br>
    <%= f.select :institution_id, Institution.ordered.pluck(:name, :id) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.radio_button :gender, 'Male' %> Male
    <%= f.radio_button :gender, 'Female' %> Female
    <%= f.radio_button :gender, '' %> Not set
  </div>
  <div class="field">
    <%= f.label :branch %>
    <%= f.radio_button :branch, 'Sciences' %> Sciences
    <%= f.radio_button :branch, 'Humanitites' %> Humanities
    <%= f.radio_button :branch, '' %> Not set
  </div>

  <div class="field">
    <%= f.label :year_of_birth %><br>
    <%= f.number_field :year_of_birth %>
  </div>

  <div class="field">
    <%= f.check_box :shortlisted %>
    <%= f.label :shortlisted %>
  </div>

  <div class="field">
    <%= f.label :shortlist_reason %><br>
    <%= f.text_area :shortlist_reason, cols: 50, rows: 4 %>
  </div>

  <div class="field">
    <%= f.label :documentation %><br>
    URL-er her blir automatisk gjort til lenker.<br>
    <%= f.text_area :documentation, cols: 50, rows: 10 %>
  </div>

  <div class="field">
    <%= f.label :attachments %><br>
    <ul>
      <%= f.fields_for :attachments do |a| %>
        <li>
        <% if a.object.persisted? %>
          <%= a.check_box :_destroy %> [Slett]
          <%= link_to a.object.file.url do %>
            <%= a.object.file_file_name %>
          <% end %>
        <% else %>
          Ny fil
        <% end %>
        <%= a.file_field :file %>
        </li>
      <% end %>
    </ul>
  </div>

  <h3>Nominasjonstekster</h3>

  <%= f.fields_for :reasons do |ff| %>
    <fieldset>
    <div class="field">
      <%= ff.label :reason %><br>
      <%= ff.text_area :reason, cols: 40, rows: 10 %>
    </div>
    <div class="field">
      <%= ff.label :nominator %><br>
      <%= ff.text_field :nominator %>
    </div>
    <div class="field">
      <%= ff.label :nominator_email %><br>
      <%= ff.text_field :nominator_email %>
    </div>
    <div class="field">
      <%= ff.label :verified %><br>
      <%= ff.check_box :verified %>
    </div>
    <div class="field">
      <%= ff.label :verified, 'Slett' %><br>
      <%= ff.check_box :_destroy %>
    </div>
    </fieldset>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nominations/_nomination.html.haml
.nomination
  %h2
    = nomination.name
    %small== ID: #{nomination.id}
  %p.institution= nomination.institution.name
  %p.personalia= personalia(nomination)
  %p.votes
    == #{nomination.votes} stemmer
    == (##{nomination.rank})
  - if nomination.reasons.any?
    %ol= render partial: 'report_reason', collection: nomination.reasons

app/views/nominations/_reason.html.erb
<li class="reason <%= reason.verified? ? 'verified' : 'unverified' %>">
  <em>
    <%= mail_to reason.nominator_email, reason.nominator %>
  </em>
    <%= l reason.created_at %>
  <blockquote><%= simple_format(reason.reason) %></blockquote>

  <% if can? :update, reason.nomination %>
    <p>
      <% if reason.verified? %>
        <% verb = 'Fjern godkjenning' %>
      <% else %>
        Ikke godkjent
        <% verb = 'Godkjenn' %>
      <% end %>
      <%= form_for(reason.nomination) do |f| %>
        <%= f.fields_for :reasons, reason do |reason_fields| %>
          <%= reason_fields.hidden_field :verified, value: !reason.verified %>
        <% end %>
        <%= f.button verb, type: :submit %>
      <% end %>
    </p>
  <% end %>
</li>

app/views/nominations/_report_reason.html.haml
%li.report_reason{class: report_reason.verified? ? 'verified' : 'unverified'}
  %em
    = mail_to report_reason.nominator_email, report_reason.nominator
    = l report_reason.created_at, format: :short

  %blockquote= simple_format(report_reason.reason)

app/views/nominations/_shortlist_report_nomination.html.haml
%p
%article.nomination
  %h2= nomination.name

  %dl
    %dt Institusjon
    %dd= nomination.institution.name

    %dt Stemmer
    %dd== #{nomination.votes} (##{nomination.rank} av #{Nomination.count})

    %dt Personalia
    %dd
      = personalia(nomination)
      &nbsp;

    %dt Nominasjonstekster
    %dd
      %br
      %ol= render partial: 'report_reason', collection: nomination.reasons

    %dt Begrunnelse for kortlisting
    %dd
      %br
      = simple_format(nomination.shortlist_reason)
      &nbsp;

    %dt Dokumentasjon
    %dd
      %br
      = simple_format(auto_link(nomination.documentation || ''))
      &nbsp;

    %dt Vedlegg
    %dd
      %br
      %ul
        - nomination.attachments.each do |att|
          %li= link_to att.file_file_name, att.file.url

app/views/nominations/edit.html.erb
<h1>Editing Nomination</h1>

<%= render 'form' %>

<%= link_to 'Show', @nomination %> |
<%= link_to 'Back', nominations_path %>

app/views/nominations/full_report.html.haml
%h1==  Alle #{@nominations.count} godkjente nominasjoner

= link_to '[Tilbake]', nominations_path

<p>
<button onclick='window.print()'>Skriv ut</button>
</p>

%p
  %small= DateTime.now.strftime('%d.%m.%Y %H:%M')

= render partial: 'nomination', collection: @nominations

app/views/nominations/index.html.erb
<h1><%= @title || "Nominasjoner" %></h1>

<p>
  <%= link_to_unless_current 'List alle', nominations_path %> |
  <%= link_to_unless_current 'Kortliste', shortlist_nominations_path %> |
  <%= link_to 'Full rapport', full_report_nominations_path %>
</p>


<p><%= @nominations.count %> nominasjoner</p>

<%= form_tag merge_nominations_url, method: :patch, data: { confirm: 'Helt sikker?' } do %>
  <table>
    <thead>
      <tr>
        <th>
          <% if can? :edit, Nomination %> 
            <%= submit_tag 'Smelt' %>
          <% end %>
        </th>
        <th><%= sorting_link 'Institusjon', 'institution' %></th>
        <th><%= sorting_link 'Navn', 'name' %></th>
        <th><%= sorting_link 'Nominasjoner', 'reasons' %></th>
        <th><%= sorting_link 'Stemmer', 'votes' %></th>
      </tr>
    </thead>

    <tbody>
      <% @nominations.each do |nomination| %>
        <% if can? :read, nomination %>
          <tr class='<%= cycle %w(odd even)%>'>
            <td>
              <% if can? :edit, nomination %>
                <%= check_box_tag 'ids[]', nomination.id %>
              <% end %>
            </td>
            <td><%= nomination.institution.abbreviation %></td>
            <td><%= link_to nomination.name, nomination %></td>
            <td><%= nomination.reasons.count %></td>
            <td><%= nomination.votes %></td>
            <td><%= personalia(nomination) %></td>
            <% if can? :edit, nomination %>
              <td><%= link_to 'Rediger', edit_nomination_path(nomination) if can? :edit, nomination %></td>
            <% end %>
            <% if can? :destroy, nomination %>
              <td><%= link_to 'Slett', nomination, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, nomination %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>


<p>&nbsp;</p>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @nominations %>
  </div>
  <%= will_paginate @nominations, :container => false %>
</div>


<p>
<% if can? :update, Nomination %>
  <%= button_to "Verify all",
        verify_all_nominations_path,
        method: :post,
        data: { confirm: "Er du sikker?" }
  %>
<% end %>
</p>

<% if can? :create, Nomination %>
  <%= link_to 'Ny nominasjon', new_nomination_path %>
<% end %>

app/views/nominations/new.html.erb
<h1>New Nomination</h1>

<%= render 'form' %>

<%= link_to 'Back', nominations_path %>

app/views/nominations/shortlist_report.html.haml
%h1 Kortlisten med begrunnelser

= render partial: "shortlist_report_nomination", collection: @nominations, as: :nomination

app/views/nominations/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @nomination.name %></h2>
<p>
<% if can? :update, @nomination %>
  <%= link_to 'Rediger', edit_nomination_path(@nomination) %>
<% end %>

<% if can? :destroy, @nomination %>
  <%= link_to 'Slett', @nomination, method: :delete, data: { confirm: 'Er du sikker?' } %>
<% end %>
</p>

<p>
  <strong>Institusjon:</strong>
  <%= @nomination.institution.name %>
</p>

<p>
  <strong>Navn:</strong>
  <%= @nomination.name %>
</p>

<p>
  <strong>Personalia:</strong>
  <%= personalia(@nomination) %>
</p>

<p>
  <strong>Stemmer:</strong>
  <%= @nomination.votes %>
  (#<%= @nomination.rank %> av <%= Nomination.count %>)
</p>


<p>
  <strong>Shortlistet?</strong>
  <%= @nomination.shortlisted? ? "Ja" : "Nei" %>
</p>

<p>
  <strong>Begrunnelse for shortlisting:</strong><br/>
  <%= simple_format @nomination.shortlist_reason %>
</p>

<p>
  <strong>Dokumentasjon og utdyping:</strong><br/>
  <%= auto_link(simple_format(@nomination.documentation)) %>
</p>

<p>
  <strong>Vedlegg:</strong>
  <% if @nomination.attachments.any? %>
    <ul>
      <% @nomination.attachments.each do |att| %>
        <li><%= link_to att.file_file_name, att.file.url %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<h2>Nominasjoner</h2>

<ol>
  <%= render partial: 'reason', collection: @nomination.reasons.accessible_by(current_ability) %>
</ol>

<%= link_to 'Tilbake', nominations_path %>